### ISSUE TITLE
Request: Change log for the GitHub

### ISSUE THREAD

**Issue by MikeStirner** [Medvedev91/timetome#26]
If we can have a change log so that we can see what changed from the previous version to the next, that would be awesome. It would go right here? 
https://github.com/appstome/timetome-app/releases

And if you could also make it so that F-Droid has a quick way to get to the change log, that would be cool as well.

**Comment by appstome** [comment]
I plan to add this directly to the app. Maybe already in the next release.

**Comment by Medvedev91** [comment]
The last version with in-app changelog is available in all stores.
