### ISSUE TITLE
Please add an encrypted auto backup option

### ISSUE THREAD

**Issue by 0xRustlang** [Medvedev91/timetome#36]
It will be great if the app create an folder automatically and put encrypted zip archives of backups in it.

So the user can use something like Foldersync, dropsync or other apps to sync backups automatically to cloud.

This will be great in case of sudden phone issues, theft, etc

Thank you

**Comment by Medvedev91** [comment]
At the moment, the app creates a folder automatically in the downloads and back up daily.
