### ISSUE TITLE
Can I export recorded data?

### ISSUE THREAD

**Issue by qinyuchu999** [Medvedev91/timetome#40]
Recommended by a friend to try, this is an exquisite and practical software, but I would like to know if it can export recorded data, such as CSV or Excel, etc., so that it can communicate with other software.

**Comment by Medvedev91** [comment]
Yes, you can create a backup. It's a plain .json file.

**Comment by qinyuchu999** [comment]
This is good news, but I don’t see the relevant options to export data. How
do I export it?

Thanks for your reply and have a nice day.

**Comment by qinyuchu999** [comment]
It works!
