### ISSUE TITLE
Is it possible to have two or more tasks on going at the same time?

### ISSUE THREAD

**Issue by denizenging** [Medvedev91/timetome#41]
I use this app to keep track of time of everything I would like to see statistically. For instance, I'd like to see how much time I spend each day on bus. While I do that so, I also study Japanese. I wanna have a goal of 30 minutes of Japanese each day. While I'm in the bus, most of the time I study Japanese. But I also study Japanese when I'm home. In order to fill the requirement that I study 30 minutes of Japanese, I need to be able to somehow link the time I spend on the bus to the one I spend on learning Japanese.

This could be a feature request if there's no way to achieve my goal. I thought of creating a new, blend of two tasks but that wouldn't fill the goal of 30m of Japanese alone. I'd need to somehow like divide that into two and fill individual goals.

**Comment by Medvedev91** [comment]
At this time, the app doesn't provide a way to solve your requirements. So it's better use another app focused on time tracking, like atracker.

Some day I will add a feature to the summary to filter by task name. So you will be able to see statistics only for "Japanese" task no matter which activity it was.

Also I will add an customized "hints" the the home screen. So you will be able to start "Japanese" task in one tap.

Like that :)

**Comment by ConEstArthur** [comment]
You may wanna try a different app for that. Since this one doesn't currently lacks the option.
I'd suggest Simple Time Tracker.
It's open source and has the toggle for "Allow Multi-tasking".

**Comment by denizenging** [comment]
> You may wanna try a different app for that. Since this one currently lacks the option.
> I'd suggest Simple Time Tracker.
> It's open source and has the toggle for "Allow Multi-tasking".

Sorry for the late replies. I have checked the app you mentioned out, but it doesn't funtion similar to a pomodoro timer, and neither does it have a dedicated pomodoro timer. It does, however, have exactly what I want in timetome.

**Comment by denizenging** [comment]
> At this time, the app doesn't provide a way to solve your requirements. So it's better use another app focused on time tracking, like atracker.
> 
> Some day I will add a feature to the summary to filter by task name. So you will be able to see statistics only for "Japanese" task no matter which activity it was.
> 
> Also I will add an customized "hints" the the home screen. So you will be able to start "Japanese" task in one tap.
> 
> Like that :)

Maybe you might've misunderstood me. Basically what I'm talking about is progressing in more than one goal at the same time. I believe it is not possible at the moment. Also, atracker appers to be non-floss.
