### ISSUE TITLE
Explain the mysterious lightning bolt

### ISSUE THREAD

**Issue by irisdominguez** [Medvedev91/timetome#48]
Maybe I have missed it, but I cannot find anywhere an explanation on the small lightning bolt under the tasks. I like when it goes up and dislike when it goes down, but I have absolutely no idea of when that's happening :sweat_smile: .

If you could explain this small number, and possibly include it in the general explanation of the app, that would be amazing.

Apart from that, I want to take the opportunity to thank you for creating such an amazing app.

**Comment by Medvedev91** [comment]
Nothing mysterious, just the battery level. ;)

**Comment by irisdominguez** [comment]
And here I was thinking that it was some strange algorithm on how much time you were wasting without renewing the timer or something. Ok, I think that makes sense, and most people will probably realize the connection (unlike me). Thanks!

**Comment by Medvedev91** [comment]
It turns red when the level is under 20, blue while charging and green when fully charged.
